name: Deploy Cloud Functions

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g firebase-tools
          npm install eslint --save-dev
          
      - name: Add npm bin directory to PATH
        run: echo "::add-path::$(npm bin)"

      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json

      - name: Deploy Firebase Functions
        run: |
         export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
         npx firebase use petszone-arg
         npx firebase deploy --only functions --json
