name: Deploy Cloud Functions

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: '**'

      - name: Set up service account key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/gcloud.json

      - name: Authenticate with Firebase
        run: npx firebase login:ci --no-localhost --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy Cloud Functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
          npm install -g firebase-tools
          firebase use petszone-arg
          npx firebase deploy --only functions --json
